version: '3'
services:
  web-server:
    build: .
    command: npm start
    volumes:
      - ./:/usr/src/app
    ports:
      - '8080:5000'
    depends_on:
      - mongo
    links:
      - "mongo"
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - '5000:8081'

volumes:
  data-volume: null
